server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    charset utf-8;

    location = / {
        try_files /index.html =404;
    }

    location /_list/ {
        alias /usr/share/nginx/html/;
        autoindex on;
        autoindex_exact_size off;
        autoindex_localtime on;
        autoindex_format json;
        index nonexistent;
    }

    location / {
        try_files $uri =404;
    }
}